#!/bin/bash
uri="http://andy753421.ath.cx/vpaste/"
if [ "$1" ]; then
	out=$(curl -F "x=<$1" "$uri")
else
	out=$(curl -F 'x=<-' "$uri")
fi
echo "$out"
if [ -x "`which xclip 2>/dev/null`" -a "$DISPLAY" ]; then
	echo -n "$out" | xclip -i -selection primary
	echo -n "$out" | xclip -i -selection clipboard
fi
